import SiteSheetHeader from '../components/site-sheet/Header'
import SiteSheetFooter from '../components/site-sheet/Footer'
import { useSEO } from '../hooks/useSEO'
import '../styles/site-sheet.css'

const SEO_TITLE = 'Terms of Service – PriceM8'
const SEO_DESCRIPTION = 'The terms that apply when you use PriceM8.'

export default function TermsOfService() {
    useSEO({ title: SEO_TITLE, description: SEO_DESCRIPTION, path: '/terms-of-service' })

    return (
        <div className="ps-page">
            <SiteSheetHeader />

            <main id="top">
                <section>
                    <div className="wrap">
                        <p className="mono hero-eyebrow">Legal</p>
                        <h1 className="disp" style={{ fontSize: 'var(--fs-h2)', marginBottom: 32 }}>Terms of Service</h1>

                        <div className="prose">
                            <p className="mono" style={{ marginBottom: 24 }}>
                                Last updated: {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
                            </p>

                            <p>
                                Welcome to PriceM8. By using this website (pricem8.uk) and the application, you agree to be bound by the following terms and conditions.
                            </p>

                            <h3>1. Acceptance of Terms</h3>
                            <p>
                                By accessing or using PriceM8, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you are using the service on behalf of a business, you represent that you have the authority to bind that business to these terms.
                            </p>

                            <h3>2. Description of Service</h3>
                            <p>
                                PriceM8 provides estimating and quoting software for UK landscapers and garden room builders — automatic material and labour takeoffs, live-ish material pricing you can override, and branded PDF quote and invoice generation.
                            </p>

                            <div className="note-box" style={{ margin: '2em 0' }}>
                                <p style={{ margin: 0 }}>
                                    <strong>3. Accuracy &amp; estimation disclaimer.</strong> PriceM8 is a decision-support tool.
                                    While every effort is made to provide accurate material prices and calculation logic
                                    (e.g. soil bulking, wastage), all estimates generated by the software are <strong>indicative
                                    only</strong>.
                                    <br /><br />
                                    You, the user, are solely responsible for verifying the final figures, material quantities,
                                    and labour hours before providing a quote to a client. PriceM8 accepts no liability for
                                    financial losses, under-quotes, or project overruns resulting from use of the software.
                                </p>
                            </div>

                            <h3>4. Subscriptions and Payments</h3>
                            <ul>
                                <li><strong>Fees:</strong> the Landscaping subscription is billed monthly at £25/month, after a 14-day free trial. Garden Rooms is a separate £99 one-off purchase, available once subscribed.</li>
                                <li><strong>Cancellations:</strong> you can cancel your subscription at any time through your account settings. Access continues until the end of the current billing period.</li>
                                <li><strong>Refunds:</strong> unless required by law, fees already paid are non-refundable.</li>
                            </ul>

                            <h3>5. User Data and Intellectual Property</h3>
                            <p>
                                You retain all ownership rights to the data you input into PriceM8 (customers, quotes, material lists). By using the service, you grant a license to host and process this data as necessary to provide the service.
                            </p>
                            <p>
                                The PriceM8 platform, including its logic, design, and code, is protected by copyright law.
                            </p>

                            <h3>6. Account Security</h3>
                            <p>
                                You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. Notify PriceM8 immediately of any unauthorized use.
                            </p>

                            <h3>7. Termination</h3>
                            <p>
                                PriceM8 reserves the right to suspend or terminate your account if you breach these terms or use the service in a way that could harm PriceM8 or other users.
                            </p>

                            <h3>8. Governing Law</h3>
                            <p>
                                These terms are governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
                            </p>

                            <h3>9. Contact</h3>
                            <p>
                                For any questions regarding these terms: <a href="mailto:support@pricem8.uk">support@pricem8.uk</a>.
                            </p>
                        </div>
                    </div>
                </section>
            </main>

            <SiteSheetFooter />
        </div>
    )
}
