import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import pageSpec from '../data/pageSpec.json'

export default function TermsOfService() {
    // Use the navbar/footer data from pageSpec
    const navbarSection = pageSpec.sections.find(s => s.type === 'navbar')
    const footerSection = pageSpec.sections.find(s => s.type === 'footer')

    return (
        <div className="min-h-screen bg-gray-50 dark:bg-dark-bg transition-colors duration-300">
            {navbarSection && <Navbar section={navbarSection as any} />}

            <main className="pt-32 pb-20">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-8">Terms of Service</h1>

                    <div className="prose prose-lg prose-teal dark:prose-invert text-gray-600 dark:text-gray-300">
                        <p className="lead">
                            Last updated: {new Date().toLocaleDateString('en-GB', { year: 'numeric', month: 'long', day: 'numeric' })}
                        </p>

                        <p>
                            Welcome to PriceM8. By using our website (pricem8.uk) and our application services, you agree to be bound by the following terms and conditions.
                        </p>

                        <h3>1. Acceptance of Terms</h3>
                        <p>
                            By accessing or using PriceM8, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you are using the service on behalf of a business, you represent that you have the authority to bind that business to these terms.
                        </p>

                        <h3>2. Description of Service</h3>
                        <p>
                            PriceM8 provides estimation and quoting software designed specifically for UK tradespeople. Our tools include trade packs, material price tracking, and PDF quote generation.
                        </p>

                        <div className="bg-amber-50 dark:bg-amber-900/20 border-l-4 border-amber-500 p-4 my-8">
                            <h4 className="text-amber-800 dark:text-amber-400 font-bold m-0">3. Accuracy & Estimation Disclaimer</h4>
                            <p className="text-amber-700 dark:text-amber-300 m-0 text-sm mt-2">
                                PriceM8 is a decision-support tool. While we strive to provide accurate material prices and calculation logic (e.g., soil bulking, wastage), all estimates generated by the software are <strong>indicative only</strong>.
                                <br /><br />
                                You, the user, are solely responsible for verifying the final figures, material quantities, and labour hours before providing a quote to a client. PriceM8 Ltd accepts no liability for financial losses, under-quotes, or project overruns resulting from the use of our software.
                            </p>
                        </div>

                        <h3>4. Subscriptions and Payments</h3>
                        <ul>
                            <li><strong>Fees:</strong> Subscription fees are billed in advance on a monthly or annual basis.</li>
                            <li><strong>Cancellations:</strong> You can cancel your subscription at any time through your account settings. Content will remain accessible until the end of the current billing period.</li>
                            <li><strong>Refunds:</strong> Unless required by law, subscription fees are non-refundable.</li>
                        </ul>

                        <h3>5. User Data and Intellectual Property</h3>
                        <p>
                            You retain all ownership rights to the data you input into PriceM8 (customers, quotes, material lists). By using the service, you grant us a license to host and process this data as necessary to provide the service.
                        </p>
                        <p>
                            The PriceM8 platform, including its logic, design, and code, is the property of PriceM8 Ltd and is protected by copyright laws.
                        </p>

                        <h3>6. Account Security</h3>
                        <p>
                            You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.
                        </p>

                        <h3>7. Termination</h3>
                        <p>
                            We reserve the right to suspend or terminate your account if you breach these terms or use the service in a way that could harm PriceM8 or other users.
                        </p>

                        <h3>8. Governing Law</h3>
                        <p>
                            These terms are governed by and construed in accordance with the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.
                        </p>

                        <h3>9. Contact</h3>
                        <p>
                            For any questions regarding these terms, please contact us at support@pricem8.uk.
                        </p>
                    </div>
                </div>
            </main>

            {footerSection && <Footer section={footerSection as any} />}
        </div>
    )
}
